export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_RESET_ERROR_MESSAGE = 'LOGIN_RESET_ERROR_MESSAGE';
export const LOGIN_USER_SWITCH_BIOMETRICS = 'LOGIN_USER_SWITCH_BIOMETRICS';

export const CONTACT_US_RESET_ERROR_MESSAGE = 'CONTACT_US_RESET_ERROR_MESSAGE';
export const CONTACT_US_SENDMESSAGE_ERROR = 'CONTACT_US_SENDMESSAGE_ERROR';

export const VALIDATE_DEVICE_RESET_ERROR_MESSAGE = 'VALIDATE_DEVICE_RESET_ERROR_MESSAGE';
export const VALIDATE_DEVICE_ERROR = 'VALIDATE_DEVICE_ERROR';

export const USERDETAILS_SET_INFO = 'USERDETAILS_SET_INFO';
export const USERDETAILS_SET_DEFAULT_CURRENCY = 'USERDETAILS_SET_DEFAULT_CURRENCY';

export const STATEMENTS_SET_CCYCARDS_INFO = 'STATEMENTS_SET_CCYCARDS_INFO';
export const STATEMENTS_SET_CCIES_INFO = 'STATEMENTS_SET_CCIES_INFO';
export const STATEMENTS_SET_CARDS_TX_LIST = 'STATEMENTS_SET_CARDS_TX_LIST';
export const STATEMENTS_SET_CCY_TX_LIST = 'STATEMENTS_SET_CCY_TX_LIST';
export const STATEMENTS_SET_BALANCES_INFO = 'STATEMENTS_SET_BALANCES_INFO';

export const BENEFICIARIES_SET_COUNTRIES = 'BENEFICIARIES_SET_COUNTRIES';
export const BENEFICIARIES_SET_COUNTRIES_ERROR = 'BENEFICIARIES_SET_COUNTRIES_ERROR';
export const BENEFICIARIES_SET_CURRENCIES = 'BENEFICIARIES_SET_CURRENCIES';
export const BENEFICIARIES_SET_CURRENCIES_ERROR = 'BENEFICIARIES_SET_CURRENCIES_ERROR';
export const BENEFICIARIES_GET_LIST = 'BENEFICIARIES_GET_LIST';
export const BENEFICIARIES_GET_LIST_ERROR = 'BENEFICIARIES_GET_LIST_ERROR';

export const ACCOUNTBALANCE_SET_INFO = 'ACCOUNTBALANCE_SET_INFO';
export const ACCOUNTBALANCE_SET_ERROR = 'ACCOUNTBALANCE_SET_ERROR';
export const ACCOUNTBALANCE_SET_POSITIVES = 'ACCOUNTBALANCE_SET_POSITIVES';
export const ACCOUNTBALANCE_SET_NEGATIVES = 'ACCOUNTBALANCE_SET_NEGATIVES';

export const PAYMENTS_GET_LIST = 'PAYMENTS_GET_LIST';
export const PAYMENTS_GET_LIST_SUCCESS = 'PAYMENTS_GET_LIST_SUCCESS';
export const PAYMENTS_GET_LIST_ERROR = 'PAYMENTS_GET_LIST_ERROR';

export const RATES_GET_INFO = 'RATES_GET_INFO';
export const RATES_GET_ERROR = 'RATES_GET_ERROR';

export const ORDERS_GET_LIST = 'ORDERS_GET_LIST';
export const ORDERS_GET_LIST_ERROR = 'ORDERS_GET_LIST_ERROR';
export const ORDERS_GET_LIST_SUCCESS = 'ORDERS_GET_LIST_SUCCESS';